---
language: node_js
services:
  - neo4j
cache:
  yarn: true
  directories:
    - node_modules
install:
  - make install
script:
  - make test-coverage
after_success:
  - cat coverage/lcov.info | coveralls
  - make deploy-production-eu
  - make deploy-production-us
branches:
  only:
    - master
