---
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - make install
script:
  - make test-coverage
after_success:
  - cat coverage/lcov.info | coveralls
deploy:
  - make deploy
branches:
  only:
    - master
