---
service: serverless-graphql-neo4j

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  deploymentBucket: ${self:service}-artefacts-${self:provider.region}
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, 'dev'}

functions:
  graphql:
    handler: src/server.default
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-plugin-create-deployment-bucket
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    packager: 'yarn'
    includeModules: true
  defaultRegion: 'eu-west-1'
