---
service: serverless-graphql-neo4j

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, self:custom.defaultRegion}
  deploymentBucket: ${self:service}-artefacts-${self:provider.region}
  environment:
    # for mapping prod config to env_var when deploy the service
    NEO4J_URI: ${env:NEO4J_URI_PROD}
    NEO4J_USER: ${env:NEO4J_USER_PROD}
    NEO4J_PASSWORD: ${env:NEO4J_PASSWORD_PROD}

functions:
  graphql:
    handler: src/server.default
    memorySize: 256
    events:
      - http:
          path: ${self:provider.stage}/graphql
          method: post
          cors: true
      - http:
          path: ${self:provider.stage}/graphql
          method: get
          cors: true

plugins:
  - serverless-plugin-create-deployment-bucket
  - serverless-dotenv-plugin  # for loading .env in local dev
  - serverless-webpack
  - serverless-offline

custom:
  defaultRegion: 'eu-west-1'
  webpack:
    packager: 'yarn'
    includeModules: true
